export type ProjectModel={
    project_id:number |null,
    title:string,
    description:string,
    client_id:number,
    client_name:string,
    category:string[],
    skills_required:string[],
    client_country:string,
    max_budget:number,
    min_budget:number,
    status:string|null,
    created_at:string|null,
    updated_at:string|null,
    assigned_to:number|null,
    closing_price:number|null,
    proposal_count:number|null,
    completed_at:string|null,
    payment_status:string|null,
}

export const DummyProject={
    project_id:0,
    title:"",
    description:"",
    client_id:0,
    client_name:"",
    category:[""],
    skills_required:[""],
    client_country:"",
    max_budget:0,
    min_budget:0,
    status:"",
    created_at:"",
    updated_at:"",
    assigned_to:0,
    closing_price:0,
    proposal_count:0,
    completed_at:"",
    payment_status:"",
}